### ISSUE TITLE
brewservice vs homebrew-services

### ISSUE THREAD

**Issue by zimme** [jraede/brewservice#2]
So any benefit of using this instead of homebrew-services?

https://github.com/Homebrew/homebrew-services

**Comment by jraede** [comment]
Doesn't look like it. Fewer letters to type? Had I seen that before I probably wouldn't have built this, but I have some cool plans for this, like having groups of services defined per application. E.g. `brewservice start myapp` would start `mysql`, `php-fpm`, and `nginx`, for example.

**Comment by zimme** [comment]
Well, once you have grouping done maybe I'll switch to this instead. Thanks for taking the time to answer. =)
